import type { Praktik } from "@/types";

export const praktiks: Praktik[] = [
    {
        idPraktik: 1,
        namaPraktik: "Praktik Mandiri Bidan Siti",
        idNakes: 1,
        idProfesi: 1,
        alamat: "Jl. Soekarno Hatta 15",
        kota: "Malang",
        sedangBuka: true,
    },
    {
        idPraktik: 2,
        namaPraktik: "Klinik dr. Andi",
        idNakes: 2,
        idProfesi: 2,
        alamat: "Jl. Ijen 8",
        kota: "Malang",
        sedangBuka: true,
    },
    {
        idPraktik: 3,
        namaPraktik: "Klinik Gigi Senyum",
        idNakes: 3,
        idProfesi: 3,
        alamat: "Jl. Kawi 21",
        kota: "Malang",
        sedangBuka: false,
    },
    {
        idPraktik: 4,
        namaPraktik: "Klinik Anak Ceria",
        idNakes: 4,
        idProfesi: 4,
        spesialis: "Anak",
        alamat: "Jl. Bandung 5",
        kota: "Malang",
        sedangBuka: true,
    },
    {
        idPraktik: 5,
        namaPraktik: "Home Care Ns. Rina",
        idNakes: 5,
        idProfesi: 5,
        alamat: "Jl. Sulfat 30",
        kota: "Malang",
        sedangBuka: false,
    },
];
